server:
  port: 8088

logging:
  level:
    org.springframework: DEBUG
    '[org.hibernate.sql]': DEBUG
    
spring:
  messages:
    basename: messages
  security:    user:      name: username
      password: password
  
  jpa:    show-sql: true
    hibernate:      ddl-auto: create
    defer-datasource-initialization: true
  
  h2:
    console:      enabled: true
      path: /h2-console
  datasource:    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false

management:
  endpoints:    web:      exposure:        include: "*"
  